services:
  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
      shm_size: "2gb"
    container_name: gosync-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - CLIENT_URL=http://localhost:80
      - HOST=0.0.0.0
      - npm_config_fetch_retries=5
      - npm_config_fetch_retry_mintimeout=100000
      - npm_config_fetch_retry_maxtimeout=600000
      - npm_config_fetch_timeout=300000
    env_file:
      - ./Backend/.env.prod
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/logs:/app/logs
    networks:
      - gosync-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend Service (Vite + Nginx)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5000
        - NODE_ENV=production
      shm_size: "2gb"
    container_name: gosync-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
      - npm_config_fetch_retries=5
      - npm_config_fetch_retry_mintimeout=100000
      - npm_config_fetch_retry_maxtimeout=600000
      - npm_config_fetch_timeout=300000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gosync-network

networks:
  gosync-network:
    driver: bridge
